trigger:
  - main

stages:
  - stage: Terraform_deploy
    displayName: "Terraform deploy"
    dependsOn: []
    condition: succeeded()
    jobs:
      - job: TF_DEPLOY
        displayName: "Terraform deploy"
        pool:
          vmImage: "ubuntu-latest"
        variables:
          - template: pipeline-templates/variables/terraform-variables.yml
            parameters:
              environment: $(environment)
        steps:
          - template: pipeline-templates/steps/terraform-delivery-steps.yml
            parameters:
              environment: "dev"
              azureServiceConnection: "ARM_SUBSCRIPTION"
              terraformValidate: true
              terraformPlan: true
              terraformApply: true
              terraformDestroy: true
